language: php
php:
    - 7.0
    - 7.1
    - 7.2

services:
    - mysql

install:
    - composer install
    - composer require satooshi/php-coveralls --dev
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test'

script:
    - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
